spring:
  zipkin:
    base-url: http://192.168.100.100:9411/
    sender:
      type: web
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.100.100
    port: 6379


  main:
    allow-bean-definition-overriding: true
